org: vautourpascal
app: bucket-api-level-1-app
service: ${env:API_NAME}-level-1

custom:
  dotenv:
    path: ./.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-bundle

provider:
  name: aws
  profile: ${env:AWS_PROFILE}
  region: ${env:REGION}
  runtime: nodejs12.x
  stage: ${env:NODE_ENV}
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"

package:
  individually: true

functions:
  simpleSearch:
    handler: handler.simpleSearch
    events:
      - http:
          path: geo
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                regex: true
                select: true
                tags: true
                themes: true
  # advancedSearch:
  #   handler: handler.advancedSearch
  #   events:
  #     - http:
  #         path: geo
  #         method: post
  #         cors: true
