service: ${env:API_NAME}-level-1

custom:
  dotenv:
    path: ./.env

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-bundle

provider:
  name: aws
  profile: ${env:AWS_PROFILE}
  region: ${env:REGION}
  runtime: nodejs12.x
  stage: ${env:NODE_ENV}
  versionFunctions: false

package:
  individually: true

functions:
  getAll:
    handler: handler.getAll
    events:
      - http:
          path: geo
          method: post
          cors: true
